### ISSUE TITLE
Internal Server Error in 4.38.0

### ISSUE THREAD

**Issue by Nunocky** [kasancode/gitbucket-label-kanban-plugin#16]
I'm getting an Internal Server Error with GitBucket 4.38.0. Is it a side effect of being able to specify multiple Assignees?

I am using machine translation. Sorry if my grammar is wrong.

**Comment by Nunocky** [comment]
I'm running gitbucket on apache tomcat 9. I will attach the catalina error log for your reference.
[catalina-kanban.txt](https://github.com/kasancode/gitbucket-label-kanban-plugin/files/9543707/catalina-kanban.txt)

**Comment by zsmahi** [comment]
I'm facing the same issue, did anyone fix it ? @kasancode  & @Nunocky
