### ISSUE TITLE
the download page is to gitbucket-gantt-plugin plugin

### ISSUE THREAD

**Issue by xingdaos** [kasancode/gitbucket-label-kanban-plugin#2]
the download page is to gitbucket-gantt-plugin plugin
![image](https://user-images.githubusercontent.com/33388842/47430237-635a5f00-d7cb-11e8-9910-6194e831820b.png)
![image](https://user-images.githubusercontent.com/33388842/47430288-78cf8900-d7cb-11e8-958d-5306fc384b1e.png)

**Comment by kasancode** [comment]
Thank you for the information.
I've fixed this issue.
