### ISSUE TITLE
More compact style

### ISSUE THREAD

**Issue by aadrian** [kasancode/gitbucket-label-kanban-plugin#3]
Please make the styling more compact, so that more issues fit on the board witout scrolling.

Thank you.

**Comment by kasancode** [comment]
[2.0.3](https://github.com/kasancode/gitbucket-label-kanban-plugin/releases/tag/2.0.3) support compact style.
If there are more than 10 issues in the repository, the compact style is enabled.

**Comment by aadrian** [comment]
@kasancode thank you for the new release.
