### ISSUE TITLE
order column / row

### ISSUE THREAD

**Issue by yvsppt** [kasancode/gitbucket-label-kanban-plugin#6]
I just installed this plugin. And I notice the order of displaying the columns and done using the alphabetical order.

I was wondering if it was not possible to force a column display order.

for now I added a subprefix to get the following labels:
@ 0: todo
@ 1: in progress
@ 2: testing
@ 3: ready
@ 4: done

But on kanban view, the number are superflouers

An idea is to use @position@lanename to store the position

**Comment by kasancode** [comment]
In new version, Label lanes are ordered by ID (Usually, label ID is in order of addition).
Please try version 2.0.5.

**Comment by yvsppt** [comment]
Thank you for this update. 

This behavior is not better than previous because I added a column to insert it between two already exist column. So using an order based on id of label put this column at the end of table:

@1:todo | @2:in progress | @5:done | @4:to deploy | @3:test

**Comment by kasancode** [comment]
In version 3.2.0, you can change lane order by click buttons on lane header.
Please try it.

**Comment by yvsppt** [comment]
It works fine.
Thank you for this update.
